### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pdelteil** [authcov/authcov#1]
I'm getting this error:

> puppeteer@1.19.0 install /usr/local/lib/node_modules/authcov/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r674921! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/authcov/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/authcov/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/authcov/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/authcov/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.19.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-08-22T21_49_48_551Z-debug.log

**Comment by evanrolfe** [comment]
Hi, sorry for the late reply - I've been on holiday.. This error is due to your npm permissions configuration. See this guide for fixing:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Also here are two related issues for the same issue but in the puppeteer repo (which this project relies on):
https://github.com/GoogleChrome/puppeteer/issues/367
https://github.com/GoogleChrome/puppeteer/issues/375

**Comment by evanrolfe** [comment]
Closing, as this issue is not specific to Authcov.
